Desktop version 3
AckonSamuel/Hello-Portfolio pull request #6
Opened 2022-01-17 09:34 UTC by AckonSamuel

2022-01-17 10:44 UTC, micheaol requested changes
Hi @AckonSamuel , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 
- Your repo is professional 
- Well structured files 
- You set up linter files and no errors. 


## Required Changes ♻️

- _Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-17 10:44 UTC, micheaol commented on index.html
> +                            <div class="word worddesk"><p>See this project</p></div>
Please ensure that the `See this project ->` should be a button that takes you to the Live Demo of the featured project or to the GitHub repository.

2022-01-17 10:44 UTC, micheaol commented on index.html
> -                    <div class="word"><p>See this project</p></div>
Please ensure that the `See this project ->` should be a button that takes you to the Live Demo of the featured project or to the GitHub repository.

2022-01-17 10:44 UTC, micheaol commented on index.html
> -                <div class="nameP"><h3>Project name goes here</h3></div>
Please ensure you replicate the design as much as possible (e.g., font, colors, images, buttons, margins) [using the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9). Please ensure to align` projects` as in the Figma template.

Your Implementation | Figma Design
:---:|:---:
![your-design](https://user-images.githubusercontent.com/10332499/149752679-1ef931ab-e61d-4321-95a2-e7e2d0b55921.PNG) | ![figma](https://user-images.githubusercontent.com/10332499/149752733-b6c29ab1-ec6f-4145-8155-4dd34d9a5fec.PNG).

2022-01-17 10:44 UTC, micheaol commented on index.html
>            <div>Start collaboration</div></div>
Please ensure that the `Start collaboration` be a button according to the requirement.

2022-01-17 10:44 UTC, micheaol commented on index.html
> +            <div>Start collaboration</div></button>
Please note that it is semantically incorrect to put a `<div>` inside of a `<button>`. I also observed that you have some `a` tags with `<div>` inside of them. Please note that this is not correct semantically.

2022-01-17 10:44 UTC, micheaol commented on index.html
> +                   <div class="tech1 tech1desk"><li class="maybe"><p>JavaScript</p></li></div>
Please note that it is not semantically correct to have `p` tags wrapped inside `li`. Kindly make necessary changes to all where it applies.

2022-01-18 09:02 UTC, brytebee approved these changes
Hi, @AckonSamuel👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-18 09:31 UTC, merged